# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("donations", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        )
    ]
